### ISSUE TITLE
Variable for traceID

### ISSUE THREAD

**Issue by eremeevfd** [GoogleCloudPlatform/cloud-trace-data-source-plugin#1]
Hello guys, it's a great and long waited datasource for grafana, thank you very much!

I understand that it's just first version of this plugin so I have a question:
Is it possible or would it be possible to set trace id from variable?

**Comment by xiangshen-dk** [comment]
Hi @eremeevfd ,

Thanks for the feedback! Currently, variables are not supported. However, it's just the first version as you mentioned. :)

I will tag this issue as a feature request.

**Comment by eremeevfd** [comment]
@xiangshen-dk thank you!

**Comment by xiangshen-dk** [comment]
Variable support for project id and trace id has been added. For trace id, it needs to be a text input and project ids can be get from a query.
